#https://github.com/revolunet/create-react-app-circleci/blob/master/.circleci/config.yml
# 给当前node_modules 一个快照，如果 package.json 没变，node_modules 就不用重新下载
defaults: &defaults
  docker:
    - image: circleci/node:12.18.2

version: 2
jobs:
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
      - run: npm install -D @cloudflare/wrangler --registry.npmjs.org
      - run: echo $API_TOKEN | npx wrangler config
      - run: npx wrangler publish



workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - publish